version: '3.7'


services:
  database:
    image: postgres
    enviroment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grupogazin
    ports:
      - 5432:5432

  monorepo:
    container_name: grupogazin
    build:
      context: .
      target: development
    volumens:
      - .://grupogazin/monorepo
