version: '3.7'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grupogazin
    ports:
      - 5432:5432

  monorepo:
    container_name: grupogazin
    build:
      context: .
      target: development
    volumes:
      - .://grupogazin/monorepo
      - /grupogazin/monorepo/node_modules
    ports:
      - 4200:4200
      - 3000:3000
    depends_on:
      - database
    
    
